spring:
  config:
    import: "consul:localhost:8500"
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: eventiq-worker-events

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        prefer-ip-address: false
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}-${server.port}
      config:
        enabled: true
        format: yaml
        data-key: data

    function:
      definition: processEvent

    stream:
      default:
        binder: kafka

      bindings:
        processEvent-in-0:
          destination: eventiq-events-topic
          group: event-workers
          content-type: application/json
          consumer:
            batch-mode: true

      kafka:
        bindings:
          processEvent-in-0:
            consumer:
              batch-mode: true
              max-poll-records: 10  # Optional, for controlling batch size

      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: localhost:9092

server:
  port: 9055
